version: "3"
services:
  batch-address:
    build: .
    environment:
      AWS_ACCESS_KEY: 
      AWS_SECRET_KEY: 
      AWS_REGION: us-east-1
      AWS_SQS_ADDRESS_TEST_REQUEST: "dev-address-test-request"
      AWS_SQS_ADDRESS_TEST_REQUEST_FAILURE: "dev-address-test-request-failure"
      AWS_SNS_ADDRESS_TEST_SUCCESS: 
      AWS_SNS_ADDRESS_TEST_FAILURE: 
      GOOGLE_CIVIC_INFO_API_KEY: 
    ports:
      - 10000:10000
