version: "3"
services:
  batch-address:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      RABBITMQ_PORT_5672_TCP_PORT: 5672
      VIP_BA_RABBITMQ_EXCHANGE: events
    ports:
      - 10000:10000

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - 45672:5672
      - 55672:15672
    hostname: rabbitmq
